config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'users#index'
  get '/users/query', to: 'users#query', as: 'root'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update', as: 'update_user'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/token.rb
class Token < ApplicationRecord
  belongs_to :user
  validates :nonce, presence: true, uniqueness: true

  def self.generate(user)
    while true
      nonce = SecureRandom.uuid
      token_search = Token.find_by(nonce: nonce)
      if token_search == nil
        break
      end
    end
    Token.create(:user_id => user.id, :nonce => nonce)
  end

  def self.consume(nonce)
    found_token = Token.find_by(nonce: nonce)
    if found_token
      set_user_id = found_token.user_id
      token_retrieved_user = User.find_by(id: set_user_id)
      found_token.destroy
      token_retrieved_user
    else
      nil
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_one :token
  validates :email, uniqueness: true, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :warning, :danger, :info
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    redirect_to root_path
  end

  def query
    email = params[:email]
    nonce = params[:token]
    user = User.find_by(email: email)
    token_user = Token.consume(nonce)
    if user && token_user && user.id == token_user.id
      redirect_to edit_user_path(user)
    end
  end

  def edit
    user_id = params[:id]
    @user = User.find_by_id(user_id)
    @token = Token.generate(@user)
  end

  def update
    email = params[:email]
    nonce = params[:token]
    new_email = params[:new_email]
    user = User.find_by(email: email)
    token_user = Token.consume(nonce)
    if user && token_user && user.id == token_user.id
      if email != new_email
        email_user = User.find_by(email: new_email)
        if email_user
          flash[:error] = 'That email is already in use. Please choose another email address.'
          return redirect_to edit_user_path(user)
        end
      end
      user.update_attributes(user_params)
      flash[:notice] = 'Your changes have been saved.'
      return redirect_to edit_user_path(user)
    else
      flash[:error] = 'User not found.'
    end
  end

  private

  def user_params
    user_attributes = params.permit(:name, :receiveMarketing, :receiveArticles, :receiveDigest)
    user_params = user_attributes.merge({email: params[:new_email], receiveMarketing: !!params[:receiveMarketing], receiveArticles: !!params[:receiveArticles], receiveDigest: !!params[:receiveDigest]})
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(flash_type)
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmailPickerRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= image_tag("TheInformationLogo.png", :alt => "The Information") %>
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-8 offset-lg-2">
          <h3>Email is a critical communications channel for <span>The Information</span>. We want our subscribers to have control of when they hear from us and what kind of emails they receive.</h3>
        </div>
      </div>
    <div class="row">
      <div class="col-lg-6 offset-lg-3 col-sm-12">
      <p>
        <% if flash[:error] %>
          <div class="alert alert-<%= bootstrap_class_for(:error) %> fade in">
          <button class="close" data-dismiss="alert">×</button>
            <p class="notice"><%= flash[:error] %></p>
          </div>
        <% end %>
        <% if flash[:notice] %>
          <div class="alert alert-<%= bootstrap_class_for(:notice) %> fade in">
          <button class="close" data-dismiss="alert">×</button>
            <p class="notice"><%= flash[:notice] %><p>
          </div>
        <% end %>
      </p>
    </div>
  </div>
</div>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-6 offset-lg-3 col-sm-12">
      <hr>
      <h3>Change Your Email Preferences</h3>
      <p>These are your current settings. Feel free to update them and click "submit"!</p>

      <!-- Needs checkbox for no email option -->
      <%= form_tag(update_user_path, :method => "patch") do %>
        <%= hidden_field_tag 'email', @user.email %>
        <%= hidden_field_tag 'token', @token.nonce %>
        <%= label_tag('new_email', "Email Address:") %>
        <%= text_field_tag('new_email', @user.email, class: 'form-control input-medium') %><br>
        <%= check_box_tag 'receiveMarketing', '1', @user.receiveMarketing %>
        <%= label_tag(:receiveMarketing, "I would like to receive special offers from The Information.") %><br>
        <%= check_box_tag 'receiveArticles', '1', @user.receiveArticles %>
        <%= label_tag(:receiveArticles, "I would like to receive an email when a new article is published.") %><br>
        <%= check_box_tag 'receiveDigest', '1', @user.receiveDigest %>
        <%= label_tag(:receiveDigest, "I would like to receive a digest of the week's news every Saturday.") %><br>
        <%= radio_button_tag("opt_out", true)%>
        <%= label_tag("Do not email me.") %><br>
        <%= submit_tag "Save Changes", :class => "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
<br>

app/views/users/query.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-6 offset-lg-3 col-sm-12">
      <hr>
      <h3>Let's start by pulling up your current email settings.</h3>
      <p>You can query a user's account with their email and token nonce in the url.<p>
      <p>For example:</p><br>
      <p>
      http://localhost:3000/users/query?email=johndoe@example.com&token=e152cd41-60ad-413a-8ac4-b38fb1977cab</p>
      <p>
      http://localhost:3000/users/query?email=janedoe@example.com&token=775bc785-d7d0-441f-b324-7d48157ec980</p>
    </div>
  </div>
</div>
<br>